"""Generate the LaTeX includes built from the paper-pack tables:

  tables/cities_descriptives.tex  -- SI per-city longtable (Table S1)
  tables/city_gallery.tex         -- SI gallery of the 67 compounding maps

Rerun after any paper-pack refresh, then recompile main.tex.
"""
import csv
import pathlib

PACK = pathlib.Path("../docs/paper-pack/data")
OUT = pathlib.Path("tables")
OUT.mkdir(exist_ok=True)

# pdflatex/T1-safe replacements for the non-ASCII characters in city names
TEX = {
    "ä": r"\"a", "å": r"\r{a}", "é": r"\'e", "ó": r"\'o", "ö": r"\"o",
    "ø": r"\o{}", "ü": r"\"u", "ă": r"\u{a}", "ī": r"\={\i}", "Ł": r"\L{}",
    "ł": r"\l{}", "ź": r"\'z", "ż": r"\.z", "Ž": r"\v{Z}", "ž": r"\v{z}",
    "ș": r"\c{s}",  # comma-below approximated by cedilla (T1 has no U+0219)
}

def tex(s: str) -> str:
    return "".join("{" + TEX[c] + "}" if c in TEX else c for c in s)

rows = list(csv.DictReader(open(PACK / "cities_descriptives.csv")))

desert = {r["city"] for r in csv.DictReader(open(PACK / "cityvector_clustered.csv"))
          if r["cluster_kmeans"] == "1"}
partial = {r["city"] for r in csv.DictReader(open(PACK / "cityvector_clustered_peeled.csv"))
           if r["cluster_kmeans"] == "1"}

def grade(city: str) -> str:
    if city in desert:
        return "desert"
    if city in partial:
        return "partial"
    return "covered"

# ---------------------------------------------------------------- Table S1
with open(OUT / "cities_descriptives.tex", "w") as f:
    f.write(r"""% AUTOGENERATED by make_includes.py from
% docs/paper-pack/data/cities_descriptives.csv -- do not edit by hand.
\begin{footnotesize}
\setlength{\tabcolsep}{3.5pt}
\begin{longtable}{@{}llllr c rrrrrr@{}}
\caption{The 67 functional urban areas, largest first. Grade: emergency-periphery
coverage grade (Section~\ref{sec:coverage}); $n_{\mathrm{em}}$: number of mapped
emergency services (2 = both ED hospital and ambulance station);
$\bar D_{\mathrm{ev}}$: population-weighted mean everyday deprivation level (0--1);
$\bar C_{\mathrm{em}}$: mean emergency deprivation cost in multiples of the 15-min
benchmark cost $g(15)$; $G$: population-weighted Gini per regime; $\rho$: Spearman
coupling of the two percentile surfaces; HH: compounding population share at the
median split.}\label{tab:si-cities}\\
\toprule
City & CC & Region & Population & Grade & $n_{\mathrm{em}}$ &
$\bar D_{\mathrm{ev}}$ & $\bar C_{\mathrm{em}}$ &
$G_{\mathrm{ev}}$ & $G_{\mathrm{em}}$ & $\rho$ & HH \\
\midrule
\endfirsthead
\multicolumn{12}{l}{\emph{Table \ref{tab:si-cities} continued}}\\
\toprule
City & CC & Region & Population & Grade & $n_{\mathrm{em}}$ &
$\bar D_{\mathrm{ev}}$ & $\bar C_{\mathrm{em}}$ &
$G_{\mathrm{ev}}$ & $G_{\mathrm{em}}$ & $\rho$ & HH \\
\midrule
\endhead
\bottomrule
\endlastfoot
""")
    for r in rows:
        f.write(
            f"{tex(r['name'])} & {r['country']} & {r['region']} & "
            f"{int(r['population']):,} & {grade(r['city'])} & {r['n_emergency_services']} & "
            f"{float(r['mean_everyday']):.3f} & {float(r['mean_emergency']):.2f} & "
            f"{float(r['gini_everyday']):.3f} & {float(r['gini_emergency']):.3f} & "
            f"{float(r['spearman_rho']):.2f} & {float(r['compounding_pop_share_50']):.3f} \\\\\n")
    f.write("\\end{longtable}\n\\end{footnotesize}\n")

# ------------------------------------------------------------- city gallery
PER_FIG = 6
with open(OUT / "city_gallery.tex", "w") as f:
    f.write("% AUTOGENERATED by make_includes.py -- do not edit by hand.\n")
    for i in range(0, len(rows), PER_FIG):
        chunk = rows[i:i + PER_FIG]
        f.write("\\begin{figure}[p]\n\\centering\n")
        for j, r in enumerate(chunk):
            f.write(f"\\includegraphics[width=0.48\\textwidth]{{{r['city']}.png}}%\n")
            f.write("\\hfill\n" if j % 2 == 0 else "\\\\[2pt]\n")
        names = ", ".join(
            f"{tex(r['name'])} ({r['country']})" for r in chunk)
        f.write(
            "\\caption{Per-city compounding maps (median-split co-location typology), "
            f"cities {i+1}--{i+len(chunk)} by population: {names}. "
            "Read for spatial pattern only; per-cell classes carry a $\\sim$24\\,\\% "
            "routing-engine flip share (E.1).}\n")
        f.write(f"\\label{{fig:si-gallery-{i//PER_FIG + 1}}}\n\\end{{figure}}\n\n")

print("wrote", OUT / "cities_descriptives.tex", "and", OUT / "city_gallery.tex")


# ------------------------------------------- regional-structure tables (SI)
# From paper/analysis_regional_structure.py outputs in the pack.
def _rows(name):
    return list(csv.DictReader(open(PACK / name)))

LABEL = {"spearman_rho": r"coupling $\rho$", "gini_everyday": "everyday Gini",
         "gini_emergency": "emergency Gini", "divergence_gap": "divergence gap",
         "compounding_pop_share_50": "HH share", "compounding_intensity":
         "compounding intensity", "mean_emergency": "mean emergency cost"}

with open(OUT / "regional_variance.tex", "w") as f:
    f.write(r"""% AUTOGENERATED by make_includes.py from regional_variance_decomposition.csv
\begin{table}[h]
\centering
\caption{Nested decomposition of the variance of each city indicator across
the 67 cities: share of the total sum of squares lying between the four
macro-regions, between countries within regions, and between cities within
countries. Source: \texttt{regional\_variance\_decomposition.csv}
(\texttt{paper/analysis\_regional\_structure.py}).}
\label{tab:si-variance}
\small
\begin{tabular}{@{}lrrrr@{}}
\toprule
Indicator & Between regions & Between countries & Within countries & Country level \\
 & & (within region) & & (regions + countries) \\
\midrule
""")
    for r in _rows("regional_variance_decomposition.csv"):
        f.write(f"{LABEL[r['indicator']]} & "
                f"{float(r['share_between_regions']):.2f} & "
                f"{float(r['share_between_countries_within_region']):.2f} & "
                f"{float(r['share_within_country']):.2f} & "
                f"{float(r['share_country_level_total']):.2f} \\\\\n")
    f.write(r"""\bottomrule
\end{tabular}
\end{table}
""")

with open(OUT / "regional_dispersion.tex", "w") as f:
    f.write(r"""% AUTOGENERATED by make_includes.py from regional_dispersion.csv
\begin{table}[h]
\centering
\caption{Dispersion of each indicator by macro-region (standard deviation
across cities) with a Fligner--Killeen test of equal dispersion at the city
level (anti-conservative reference) and the country-permutation p-value of
the same statistic (whole countries permuted across regions, 10{,}000
permutations). Source: \texttt{regional\_dispersion.csv}.}
\label{tab:si-dispersion}
\small
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
Indicator & sd North & sd West & sd South & sd CEE & $p$ city & $p_{\mathrm{perm}}$ \\
\midrule
""")
    for r in _rows("regional_dispersion.csv"):
        f.write(f"{LABEL[r['indicator']]} & {float(r['sd_North']):.3f} & "
                f"{float(r['sd_West']):.3f} & {float(r['sd_South']):.3f} & "
                f"{float(r['sd_CEE']):.3f} & "
                f"{float(r['p_fligner_city_anticonservative']):.3f} & "
                f"{float(r['p_permutation_countries']):.3f} \\\\\n")
    f.write(r"""\bottomrule
\end{tabular}
\end{table}
""")

with open(OUT / "regional_no_deserts.tex", "w") as f:
    f.write(r"""% AUTOGENERATED by make_includes.py from inference_regional_no_deserts.csv
\begin{table}[h]
\centering
\caption{Regional contrasts re-tested without the five emergency-desert
capitals (62 cities, 24 countries): ANOVA on country means and the
country-permutation p-value, with the Central-Eastern European and
rest-of-sample medians. Source: \texttt{inference\_regional\_no\_deserts.csv}.}
\label{tab:si-nodeserts}
\small
\begin{tabular}{@{}lrrrr@{}}
\toprule
Indicator & $p$ country ANOVA & $p_{\mathrm{perm}}$ & Median CEE & Median rest \\
\midrule
""")
    for r in _rows("inference_regional_no_deserts.csv"):
        f.write(f"{LABEL[r['outcome']]} & {float(r['p_country_anova']):.4f} & "
                f"{float(r['p_permutation_countries']):.4f} & "
                f"{float(r['median_CEE']):.3f} & {float(r['median_rest']):.3f} \\\\\n")
    f.write(r"""\bottomrule
\end{tabular}
\end{table}
""")

with open(OUT / "south_split.tex", "w") as f:
    f.write(r"""% AUTOGENERATED by make_includes.py from south_everyday_gini_by_country.csv
\begin{table}[h]
\centering
\caption{The 18 Southern cities ordered by everyday Gini: the Spanish and
Greek cities lie above the Italian and Portuguese ones with no overlap.
Source: \texttt{south\_everyday\_gini\_by\_country.csv}.}
\label{tab:si-south}
\small
\begin{tabular}{@{}llrrr@{}}
\toprule
City & CC & Population & $G_{\mathrm{ev}}$ & $\bar D_{\mathrm{ev}}$ \\
\midrule
""")
    for r in _rows("south_everyday_gini_by_country.csv"):
        f.write(f"{tex(r['name'])} & {r['country']} & "
                f"{int(float(r['population'])):,} & "
                f"{float(r['gini_everyday']):.3f} & "
                f"{float(r['mean_everyday']):.3f} \\\\\n".replace(",", "{,}"))
    f.write(r"""\bottomrule
\end{tabular}
\end{table}
""")

with open(OUT / "grade_by_region.tex", "w") as f:
    rows_gr = _rows("coverage_grade_by_region.csv")
    f.write(r"""% AUTOGENERATED by make_includes.py from coverage_grade_by_region.csv
\begin{table}[h]
\centering
\caption{Coverage grade by macro-region (number of cities). Source:
\texttt{coverage\_grade\_by\_region.csv}.}
\label{tab:si-grade-region}
\small
\begin{tabular}{@{}lrrr@{}}
\toprule
Region & Covered & Partial desert & Desert \\
\midrule
""")
    for r in sorted(rows_gr, key=lambda r: ["North","West","South","CEE"].index(r["region"])):
        f.write(f"{r['region']} & {r['covered']} & {r['partial desert']} & {r['desert']} \\\\\n")
    f.write(r"""\bottomrule
\end{tabular}
\end{table}
""")


# ------------------------------------ scaling robustness extras (SI, rev. 3)
OUTLAB = {"mean_everyday": "mean everyday level", "mean_emergency":
          "mean emergency cost", "gini_everyday": "everyday Gini",
          "gini_emergency": "emergency Gini"}
with open(OUT / "scaling_extra.tex", "w") as f:
    f.write(r"""% AUTOGENERATED by make_includes.py from scaling_robustness_extra.csv
\begin{table}[h]
\centering
\caption{Additional robustness of the four log-log size regressions (67
cities, country-clustered). Moran's $I$ of the residuals over the
city-centre coordinates (5 nearest neighbours, row-standardised; expected
value $-0.015$; permutation $p$, 9{,}999 draws); the elasticity with
log mapped GP density per 100k inhabitants added as a control (wild
cluster bootstrap $p$ for the elasticity; clustered $p$ for the control);
the coefficient on the squared centred log population (wild $p$); the
country-clustered Wald $p$ of three size-stratum dummies replacing log
population; and the minimum detectable elasticity at 80\,\% power
($2.80 \times$ clustered SE). Source:
\texttt{scaling\_robustness\_extra.csv}
(\texttt{paper/analysis\_scaling\_robustness.py}).}
\label{tab:si-scaling-extra}
\footnotesize
\setlength{\tabcolsep}{2.5pt}
\begin{tabular}{@{}lrrrrrrrr@{}}
\toprule
Outcome & Elast. & Moran $I$ & $p_{\mathrm{perm}}$ &
Elast.\ GP & $p_{\mathrm{wild}}$ & GP coef.\ ($p$) &
Quadr.\ ($p_{\mathrm{wild}}$) & Strata $p$ \\
\midrule
""")
    for r in _rows("scaling_robustness_extra.csv"):
        f.write(f"{OUTLAB[r['outcome']]} & {float(r['elasticity']):+.3f} & "
                f"{float(r['moran_I_resid']):+.3f} & {float(r['moran_p_perm']):.3f} & "
                f"{float(r['elasticity_gp_control']):+.3f} & "
                f"{float(r['p_wild_gp_control']):.4f} & "
                f"{float(r['gp_density_coef']):+.3f} ({float(r['gp_density_p_cluster']):.2f}) & "
                f"{float(r['quadratic_coef']):+.3f} ({float(r['p_wild_quadratic']):.2f}) & "
                f"{float(r['p_strata_wald_cluster']):.3f} \\\\\n")
    f.write(r"""\bottomrule
\end{tabular}
\end{table}
""")
with open(OUT / "scaling_crossequation.tex", "w") as f:
    f.write(r"""% AUTOGENERATED by make_includes.py from scaling_crossequation.csv
\begin{table}[h]
\centering
\caption{Cross-equation and cross-regime correlations. Residual
correlation between the everyday and the emergency size regression (with
identical regressors, joint SUR estimation coincides with OLS and this
correlation is what joint estimation adds) and the cross-city correlation
of the two within-city Ginis. Source: \texttt{scaling\_crossequation.csv}.}
\label{tab:si-crossequation}
\small
\begin{tabular}{@{}lrr@{}}
\toprule
Pair & $r$ & $p$ \\
\midrule
""")
    PAIR = {"residuals (means)": "residuals of the mean equations",
            "residuals (ginis)": "residuals of the Gini equations",
            "gini_everyday vs gini_emergency (Pearson)":
                "everyday Gini vs emergency Gini (Pearson)",
            "gini_everyday vs gini_emergency (Spearman)":
                "everyday Gini vs emergency Gini (Spearman)"}
    for r in _rows("scaling_crossequation.csv"):
        f.write(f"{PAIR.get(r['pair'], r['pair'].replace('_', ' '))} & "
                f"{float(r['pearson_r']):+.3f} & {float(r['p']):.4f} \\\\\n")
    f.write(r"""\bottomrule
\end{tabular}
\end{table}
""")
