"""Generate the LaTeX includes built from the paper-pack tables:

  tables/cities_descriptives.tex  -- SI per-city longtable (Table S1)
  tables/city_gallery.tex         -- SI gallery of the 67 compounding maps

Rerun after any paper-pack refresh, then recompile main.tex.
"""
import csv
import pathlib

PACK = pathlib.Path("../docs/paper-pack/data")
OUT = pathlib.Path("tables")
OUT.mkdir(exist_ok=True)

# pdflatex/T1-safe replacements for the non-ASCII characters in city names
TEX = {
    "ä": r"\"a", "å": r"\r{a}", "é": r"\'e", "ó": r"\'o", "ö": r"\"o",
    "ø": r"\o{}", "ü": r"\"u", "ă": r"\u{a}", "ī": r"\={\i}", "Ł": r"\L{}",
    "ł": r"\l{}", "ź": r"\'z", "ż": r"\.z", "Ž": r"\v{Z}", "ž": r"\v{z}",
    "ș": r"\c{s}",  # comma-below approximated by cedilla (T1 has no U+0219)
}

def tex(s: str) -> str:
    return "".join("{" + TEX[c] + "}" if c in TEX else c for c in s)

rows = list(csv.DictReader(open(PACK / "cities_descriptives.csv")))

desert = {r["city"] for r in csv.DictReader(open(PACK / "cityvector_clustered.csv"))
          if r["cluster_kmeans"] == "1"}
partial = {r["city"] for r in csv.DictReader(open(PACK / "cityvector_clustered_peeled.csv"))
           if r["cluster_kmeans"] == "1"}

def grade(city: str) -> str:
    if city in desert:
        return "desert"
    if city in partial:
        return "partial"
    return "covered"

# ---------------------------------------------------------------- Table S1
with open(OUT / "cities_descriptives.tex", "w") as f:
    f.write(r"""% AUTOGENERATED by make_includes.py from
% docs/paper-pack/data/cities_descriptives.csv -- do not edit by hand.
\begin{footnotesize}
\setlength{\tabcolsep}{3.5pt}
\begin{longtable}{@{}llllr c rrrrrr@{}}
\caption{The 67 functional urban areas, largest first. Grade: emergency-periphery
coverage grade (Section~\ref{sec:geography}); $n_{\mathrm{em}}$: number of mapped
emergency services (2 = both ED hospital and ambulance station);
$\bar D_{\mathrm{ev}}$: population-weighted mean everyday deprivation level (0--1);
$\bar C_{\mathrm{em}}$: mean emergency deprivation cost in multiples of the 15-min
benchmark cost $g(15)$; $G$: population-weighted Gini per regime; $\rho$: Spearman
coupling of the two percentile surfaces; HH: compounding population share at the
median split.}\label{tab:si-cities}\\
\toprule
City & CC & Region & Population & Grade & $n_{\mathrm{em}}$ &
$\bar D_{\mathrm{ev}}$ & $\bar C_{\mathrm{em}}$ &
$G_{\mathrm{ev}}$ & $G_{\mathrm{em}}$ & $\rho$ & HH \\
\midrule
\endfirsthead
\multicolumn{12}{l}{\emph{Table \ref{tab:si-cities} continued}}\\
\toprule
City & CC & Region & Population & Grade & $n_{\mathrm{em}}$ &
$\bar D_{\mathrm{ev}}$ & $\bar C_{\mathrm{em}}$ &
$G_{\mathrm{ev}}$ & $G_{\mathrm{em}}$ & $\rho$ & HH \\
\midrule
\endhead
\bottomrule
\endlastfoot
""")
    for r in rows:
        f.write(
            f"{tex(r['name'])} & {r['country']} & {r['region']} & "
            f"{int(r['population']):,} & {grade(r['city'])} & {r['n_emergency_services']} & "
            f"{float(r['mean_everyday']):.3f} & {float(r['mean_emergency']):.2f} & "
            f"{float(r['gini_everyday']):.3f} & {float(r['gini_emergency']):.3f} & "
            f"{float(r['spearman_rho']):.2f} & {float(r['compounding_pop_share_50']):.3f} \\\\\n")
    f.write("\\end{longtable}\n\\end{footnotesize}\n")

# ------------------------------------------------------------- city gallery
PER_FIG = 6
with open(OUT / "city_gallery.tex", "w") as f:
    f.write("% AUTOGENERATED by make_includes.py -- do not edit by hand.\n")
    for i in range(0, len(rows), PER_FIG):
        chunk = rows[i:i + PER_FIG]
        f.write("\\begin{figure}[p]\n\\centering\n")
        for j, r in enumerate(chunk):
            f.write(f"\\includegraphics[width=0.48\\textwidth]{{{r['city']}.png}}%\n")
            f.write("\\hfill\n" if j % 2 == 0 else "\\\\[2pt]\n")
        names = ", ".join(
            f"{tex(r['name'])} ({r['country']})" for r in chunk)
        f.write(
            "\\caption{Per-city compounding maps (median-split co-location typology), "
            f"cities {i+1}--{i+len(chunk)} by population: {names}. "
            "Read for spatial pattern only; per-cell classes carry a $\\sim$24\\,\\% "
            "routing-engine flip share (E.1).}\n")
        f.write(f"\\label{{fig:si-gallery-{i//PER_FIG + 1}}}\n\\end{{figure}}\n\n")

print("wrote", OUT / "cities_descriptives.tex", "and", OUT / "city_gallery.tex")
